CREATE TABLE public.lab_exams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  b_value integer,
  description text,
  preparation text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
GRANT SELECT ON public.lab_exams TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_exams TO authenticated;
GRANT ALL ON public.lab_exams TO service_role;
ALTER TABLE public.lab_exams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view active lab exams" ON public.lab_exams FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admins can view all lab exams" ON public.lab_exams FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "Admins can manage lab exams" ON public.lab_exams FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER update_lab_exams_updated_at BEFORE UPDATE ON public.lab_exams FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE UNIQUE INDEX lab_exams_name_unique ON public.lab_exams (lower(name));
INSERT INTO public.lab_exams (name, category, b_value, display_order) VALUES
('25 Oh Vitamine D','HORMONOLOGIE',125,0),
('Ac Anti Dna Natif','SEROLOGIE',100,1),
('Ac Anti Hav Igm (Hepatite A)','SEROLOGIE',70,2),
('Ac Anti Hbc Igm','SEROLOGIE',70,3),
('Ac Anti Hbc Totaux','SEROLOGIE',70,4),
('Ac Anti Hbe','SEROLOGIE',70,5),
('Ac Anti Récepteur de la Tsh','SEROLOGIE',150,6),
('Ac Anti Vhc (Hépatite C)','SEROLOGIE',70,7),
('Ace','HORMONOLOGIE',100,8),
('Acétone (Urines De Miction)','BIOCHIMIE',5,9),
('Acide Urique (Urines de 24h Dosage)','BIOCHIMIE',20,10),
('Acide Urique','BIOCHIMIE',10,11),
('Acth','HORMONOLOGIE',125,12),
('Afp','HORMONOLOGIE',70,13),
('Aghbs Quantitatif','SEROLOGIE',129,14),
('Aghbs','SEROLOGIE',70,15),
('Amylasémie','BIOCHIMIE',40,16),
('Amylasurie','BIOCHIMIE',45,17),
('Antibiogramme / Antifongigramme','MICROBIOLOGIE',65,18),
('Antigènes Solubles Bactériens','MICROBIOLOGIE',40,19),
('Beta 2 Microglobuline','HORMONOLOGIE',100,20),
('Beta Hcg Plasmatique','HORMONOLOGIE',100,21),
('Bilirubine Conjuguée','BIOCHIMIE',25,22),
('Bilirubine Totale','BIOCHIMIE',25,23),
('Bilirubine Urinaire','BIOCHIMIE',5,24),
('Ca 125','HORMONOLOGIE',100,25),
('Ca 15.3','HORMONOLOGIE',100,26),
('Ca 19.9','HORMONOLOGIE',100,27),
('Calcium Corrige','BIOCHIMIE',60,28),
('Calcium Ionise','BIOCHIMIE',60,29),
('Calcium Plasmatique','BIOCHIMIE',20,30),
('Calcium Urines De 24h (Dosage)','BIOCHIMIE',20,31),
('Capacité Totale de Fixation du Fer (Ctf)','BIOCHIMIE',20,32),
('Cd4/Cd8','SEROLOGIE',45,33),
('Cd4','SEROLOGIE',45,34),
('Charge Virale Hépatite C (Hvc Pcr)','SEROLOGIE',300,35),
('Charge Virale Hépatite B (Hvb Pcr)','SEROLOGIE',200,36),
('Charge Virale Hiv (Hiv Pcr)','SEROLOGIE',450,37),
('Chlorures (Cl-)','BIOCHIMIE',10,38),
('Chlorures Urines de 24h (Dosage)','BIOCHIMIE',20,39),
('Cholestérol Hdl','BIOCHIMIE',10,40),
('Cholestérol Ldl','BIOCHIMIE',35,41),
('Cholestérol Total + Fractions','BIOCHIMIE',65,42),
('Cholestérol Total','BIOCHIMIE',10,43),
('Cla-Mixte (Clatrophallergene et Clapneumallergenes)','BIOCHIMIE',150,44),
('Coombs Direct','SEROLOGIE',15,45),
('Coombs Indirect','SEROLOGIE',30,46),
('Coproculture','MICROBIOLOGIE',65,47),
('Cortisol Libre Urinaire','HORMONOLOGIE',100,48),
('Cortisol Plasmatique','HORMONOLOGIE',100,49),
('Créatine Phosphokinase (Cpk)','BIOCHIMIE',30,50),
('Créatinine (Urines de 24h Dosage)','BIOCHIMIE',30,51),
('Créatinine Clairance (Cockcroft)','BIOCHIMIE',30,52),
('Créatinine','BIOCHIMIE',10,53),
('Crp','BIOCHIMIE',10,54),
('D Dimères','HEMATOLOGIE',100,55),
('Drogues Urinaires','BIOCHIMIE',200,56),
('Electrophorèse de L''hémoglobine','HEMATOLOGIE',60,57),
('Electrophorèse des Protéines','BIOCHIMIE',60,58),
('Estradiol Plasmatique','HORMONOLOGIE',100,59),
('Examen Cytobactériologique des Urines (Ecbu)','MICROBIOLOGIE',45,60),
('Examen Cytobactériologique du Pus','MICROBIOLOGIE',65,61),
('Examen Cytobactériologique Sécrétion Urétrale (Pu)','MICROBIOLOGIE',65,62),
('Examen Cytobactériologique Sécrétion Vaginale (Pv)','MICROBIOLOGIE',65,63),
('Facteurs Rhumatoides (Test Au Latex)','SEROLOGIE',25,64),
('Facteurs Rhumatoides (Waaler Rose)','SEROLOGIE',40,65),
('Fer','BIOCHIMIE',30,66),
('Férritinemie','BIOCHIMIE',100,67),
('Fibrinogène','HEMATOLOGIE',20,68),
('Fibrotest-Actitest','BIOCHIMIE',400,69),
('Frottis Cervico Vaginal de Dépistage','CYTOLOGIE',65,70),
('G6pd','HEMATOLOGIE',70,71),
('Gamma Gt','BIOCHIMIE',25,72),
('Glucose (Urines de Miction)','BIOCHIMIE',5,73),
('Glycémie Postprandiale','BIOCHIMIE',10,74),
('Glycémie','BIOCHIMIE',10,75),
('Goutte Epaisse','MICROBIOLOGIE',25,76),
('Groupe Sanguin 1ère Détermination','HEMATOLOGIE',30,77),
('Groupe Sanguin 2ème Détermination','HEMATOLOGIE',30,78),
('Helicobacter Pylori Igg','MICROBIOLOGIE',40,79),
('Hémoculture (Aérobie Ou Anaérobie)','MICROBIOLOGIE',65,80),
('Hémoglobine Glycosylée','HEMATOLOGIE',70,81),
('Hémogramme (Nfs)','HEMATOLOGIE',30,82),
('Herpès Igg + Igm','SEROLOGIE',180,83),
('Hiv 1 / Hiv 2 Dépistage (Elfa 4eme Génération)','SEROLOGIE',70,84),
('Hormone De Croissance (Gh)','HORMONOLOGIE',150,85),
('Hyperglycémie Provoquée Par Voie Orale','BIOCHIMIE',60,86),
('Ige Totales','SEROLOGIE',100,87),
('Ionogramme Sanguin (Na+, K+, Cl-)','BIOCHIMIE',40,88),
('Microalbuminurie (24h)','BIOCHIMIE',45,89),
('Microalbuminurie de Miction','BIOCHIMIE',45,90),
('Myélogramme','HEMATOLOGIE',100,91),
('Nt Pro Bnp','HORMONOLOGIE',100,92),
('Potassium (K+)','BIOCHIMIE',15,93),
('Protéinurie (Urines de Miction)','BIOCHIMIE',5,94),
('Psa Libre + Calcul du Risque','HORMONOLOGIE',100,95),
('Psa Totale 3ème Génération','HORMONOLOGIE',100,96),
('Qbc Test / Test Rapid Malaria','MICROBIOLOGIE',25,97),
('Recherche de Chlamydiae (Urines et Sécrétions Urogénitales)','MICROBIOLOGIE',40,98),
('Recherche De Cryptocoques (Lcr)','MICROBIOLOGIE',40,99),
('Recherche de Mycoplasmes (Urines et Sécrétions Urogénitales)','MICROBIOLOGIE',100,100),
('Salmonellose (Widal Et Félix)','SEROLOGIE',40,101),
('Sang Dans Les Selles (Fit)','BIOCHIMIE',20,102),
('Sang dans Les Urines','BIOCHIMIE',20,103),
('Sérologie Amibienne','SEROLOGIE',40,104),
('Sérologie Bilharzienne','SEROLOGIE',40,105),
('Sérologie Chlamydiae Iga','SEROLOGIE',100,106),
('Sérologie Chlamydiae Igg','SEROLOGIE',60,107),
('Sérologie Chlamydiae Igm','SEROLOGIE',90,108),
('Sérologie Mycoplasme','SEROLOGIE',100,109),
('Sérologie Rubéole Igg','SEROLOGIE',50,110),
('Sérologie Rubéole Igm','SEROLOGIE',50,111),
('Sérologie Syphilis (Vdrl+Tpha)','SEROLOGIE',40,112),
('Sodium (Na+)','BIOCHIMIE',15,113),
('Spermoculture','MICROBIOLOGIE',65,114),
('Spermogramme + Spermocytogramme','CYTOLOGIE',60,115),
('Sucre (Urines de Miction)','BIOCHIMIE',5,116),
('T3 Libre Plasmatique','HORMONOLOGIE',90,117),
('T3 Totale Plasmatique','HORMONOLOGIE',90,118),
('T4 Libre Plasmatique','HORMONOLOGIE',90,119),
('T4 Totale Plasmatique','HORMONOLOGIE',90,120),
('Taux D''hémoglobine','HEMATOLOGIE',10,121),
('Taux de Plaquettes','HEMATOLOGIE',15,122),
('Taux de Prothrombine (Tp) + Inr','HEMATOLOGIE',20,123),
('Taux de Réticulocytes','HEMATOLOGIE',10,124),
('Temps de Céphaline Activée (Tca)','HEMATOLOGIE',20,125),
('Test Respiratoire à L''urée (Hélikit)','MICROBIOLOGIE',70,126),
('Testostérone Plasmatique','HORMONOLOGIE',100,127),
('Toxoplasmose Avidité des Igg','SEROLOGIE',50,128),
('Toxoplasmose Iga','SEROLOGIE',65,129),
('Toxoplasmose Igg','SEROLOGIE',50,130),
('Toxoplasmose Igm','SEROLOGIE',50,131),
('Transaminases (Sgot)','BIOCHIMIE',25,132),
('Transaminases (Sgpt)','BIOCHIMIE',25,133),
('Triglycérides','BIOCHIMIE',10,134),
('Troponine I','BIOCHIMIE',100,135),
('Tsh 3ème Génération','HORMONOLOGIE',90,136),
('Urée','BIOCHIMIE',10,137),
('Urobiligène','BIOCHIMIE',5,138),
('Vitamine B12','BIOCHIMIE',100,139),
('Vitamine B9','BIOCHIMIE',100,140),
('Vitesse De Sédimentation','HEMATOLOGIE',NULL,141);